export const CONTENTFUL_CONTENT_ENTRY_KEYS = {
  HOME: '2peFXvBUiCt2gM8eCh4NoD',
  FOUNDER: '6YLVKd81WK2Z6eASH3POSc',
  ABOUT: '70mLmJNDh6kzGJ3PxN9KHd',
  OFFERINGS: '6qaQ0UWYOj7hce14Xhq1XF',
  COACHING: 'pg5JBbPHI6MFPRVD4ByMJ',
  TRAINING: '63s5rZ2VzX3bqrCNod54wn',
  CONSULTING: '1a0Yhcvi6tHsW5HPtyokSb',
  BLOG: '65QVnOu4ILMIb3WDUANNgp',
  MANAGEMENT: '44EN2yC2OqXpqfvDhmcLM5'
}

export const CONTENTFUL_CONTENT_TYPE_KEYS = {
  BLOG_DIRECTORY: 'blogDirectoryPage',
  BLOG_POST: 'blogPost',
  TRAINING_CATEGORY: 'offeringsTrainingCategoryPage',
  TRAINING_EVENT: 'offeringsTrainingEventPage',
}